/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.payroll.business;

import javax.swing.JFrame;

/**
 *
 * @author Kashif Alei
 */
public class GeneralUserFrame extends javax.swing.JFrame {

    /**
     * Creates new form GeneralUserFrame
     */
    public GeneralUserFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //setUndecorated(true);
        userName.setText(LoginFrame.userModel.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Center = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        meetingBtn = new javax.swing.JLabel();
        attendanceBtn = new javax.swing.JLabel();
        profileBtn = new javax.swing.JLabel();
        leaveBtn = new javax.swing.JLabel();
        jPanel_UP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jPanel_Down = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel_Center.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meetingBtn.setBackground(new java.awt.Color(53, 168, 83));
        meetingBtn.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        meetingBtn.setForeground(new java.awt.Color(255, 255, 255));
        meetingBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meetingBtn.setText("Meeting");
        meetingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meetingBtn.setOpaque(true);
        meetingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meetingBtnMouseClicked(evt);
            }
        });
        jPanel2.add(meetingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 240, 120));

        attendanceBtn.setBackground(new java.awt.Color(53, 168, 83));
        attendanceBtn.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        attendanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        attendanceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendanceBtn.setText("Attendance");
        attendanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceBtn.setOpaque(true);
        attendanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceBtnMouseClicked(evt);
            }
        });
        jPanel2.add(attendanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 300, 120));

        profileBtn.setBackground(new java.awt.Color(53, 168, 83));
        profileBtn.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        profileBtn.setForeground(new java.awt.Color(255, 255, 255));
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileBtn.setText("Profile");
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.setOpaque(true);
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });
        jPanel2.add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 120));

        leaveBtn.setBackground(new java.awt.Color(53, 168, 83));
        leaveBtn.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        leaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        leaveBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaveBtn.setText("Leave");
        leaveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaveBtn.setOpaque(true);
        leaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaveBtnMouseClicked(evt);
            }
        });
        jPanel2.add(leaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 240, 120));

        jPanel_Center.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Center, java.awt.BorderLayout.CENTER);

        jPanel_UP.setBackground(new java.awt.Color(53, 168, 83));
        jPanel_UP.setPreferredSize(new java.awt.Dimension(10, 150));
        jPanel_UP.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 198, 62));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel_UP.add(jLabel5);
        jLabel5.setBounds(1300, 100, 60, 50);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logout");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel_UP.add(jLabel1);
        jLabel1.setBounds(1290, 50, 60, 30);

        userName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("jLabel7");
        jPanel_UP.add(userName);
        userName.setBounds(1110, 50, 110, 30);

        getContentPane().add(jPanel_UP, java.awt.BorderLayout.PAGE_START);

        jPanel_Down.setBackground(new java.awt.Color(53, 168, 83));
        jPanel_Down.setPreferredSize(new java.awt.Dimension(10, 40));
        jPanel_Down.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All Right Reserved © 2019 ");
        jPanel_Down.add(jLabel2, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel_Down, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void meetingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meetingBtnMouseClicked
        new UserMeetingFrame().setVisible(true);
    }//GEN-LAST:event_meetingBtnMouseClicked

    private void attendanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceBtnMouseClicked
        new UserAttendanceFrame().setVisible(true);
    }//GEN-LAST:event_attendanceBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        new UserDetailsFrame().setVisible(true);
    }//GEN-LAST:event_profileBtnMouseClicked

    private void leaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveBtnMouseClicked
        new UserLeaveFrame().setVisible(true);
    }//GEN-LAST:event_leaveBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendanceBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Center;
    private javax.swing.JPanel jPanel_Down;
    private javax.swing.JPanel jPanel_UP;
    private javax.swing.JLabel leaveBtn;
    private javax.swing.JLabel meetingBtn;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
