/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.payroll.business;

import com.payroll.dao.AttendanceDAO;
import com.payroll.daoimpl.AttendanceDAOImpl;
import com.payroll.daoimpl.UserDaoImpl;
import com.payroll.models.Attendance;
import com.payroll.models.User;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;

/**
 *
 * @author Kashif Ali
 */
public class LoginFrame extends javax.swing.JFrame {

    public static User userModel;
    private static String userType;

    /**
     * Creates new form LoginFrame
     */
    private String pattern = "yyyy-MM-dd";
    private SimpleDateFormat simpleDateFormat;
    private AttendanceDAOImpl attendanceDAO;
    public LoginFrame() {
        this.attendanceDAO = new AttendanceDAOImpl();
        this.simpleDateFormat = new SimpleDateFormat(pattern);
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setSize(491, 371);
        this.setLocationRelativeTo(null);
        lblLogin.setVisible(true);
        lblLogin.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        userField = new javax.swing.JTextField();
        lblAuthenticate = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 80));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login Form");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 130, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 30, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 30, 50));

        passField.setBackground(new java.awt.Color(250, 250, 250));
        passField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        passField.setForeground(new java.awt.Color(102, 102, 102));
        passField.setText("PASSWORD");
        passField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldKeyPressed(evt);
            }
        });
        jPanel3.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 320, 50));

        userField.setBackground(new java.awt.Color(250, 250, 250));
        userField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        userField.setForeground(new java.awt.Color(102, 102, 102));
        userField.setText("USERNAME");
        userField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFieldFocusLost(evt);
            }
        });
        userField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userFieldKeyPressed(evt);
            }
        });
        jPanel3.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 320, 50));

        lblAuthenticate.setBackground(new java.awt.Color(53, 168, 83));
        lblAuthenticate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAuthenticate.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthenticate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthenticate.setText("Sign up");
        lblAuthenticate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAuthenticate.setOpaque(true);
        lblAuthenticate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuthenticateMouseClicked(evt);
            }
        });
        jPanel3.add(lblAuthenticate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 140, 50));

        lblLogin.setBackground(new java.awt.Color(53, 168, 83));
        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setOpaque(true);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        jPanel3.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 50));

        jLabel8.setBackground(new java.awt.Color(53, 168, 83));
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 490, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldKeyPressed

    private void passFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (lblLogin.isEnabled()) {
                login();
            }

        }
    }//GEN-LAST:event_passFieldKeyPressed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        login();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void userFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusGained
        // TODO add your handling code here:
        if (userField.getText().equals("USERNAME")) {
            userField.setText("");
        }
    }//GEN-LAST:event_userFieldFocusGained

    private void userFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFieldFocusLost
        // TODO add your handling code here:
        if (userField.getText().isEmpty()) {
            userField.setText("USERNAME");
        }
    }//GEN-LAST:event_userFieldFocusLost

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        if (passField.getText().equals("PASSWORD")) {
            passField.setEchoChar(new JPasswordField().getEchoChar());
            passField.setText("");
        }
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        // TODO add your handling code here:
        if (passField.getText().isEmpty()) {
            passField.setText("PASSWORD");
            passField.setEchoChar(new JPasswordField().getEchoChar());
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void lblAuthenticateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthenticateMouseClicked
        signUp();
    }//GEN-LAST:event_lblAuthenticateMouseClicked
    private void login() {
        if ((!userField.getText().trim().equals("") || !passField.getText().trim().equals("")) && !userField.getText().contains("@")) {
            System.err.println("Checking with username");
            userModel = new User();
            userModel.setUserName(userField.getText());
            userModel.setPassword(passField.getText());
            userModel = new UserDaoImpl().loginUser(userModel);
            // 
            
            if (userModel != null && userModel.getDesignation().equalsIgnoreCase("Admin")) {
                new MainFrame().setVisible(true);
                this.dispose();
            } else if (userModel != null) {
                new GeneralUserFrame().setVisible(true);
                try {
                    Date todaysAttendaceDate = new Date();
                    String date = simpleDateFormat.format(todaysAttendaceDate);
                    String userName = userModel.getUserName();
                    Attendance attendance = new Attendance();
                    attendance.setAttendanceDate(simpleDateFormat.parse(date));
                    attendance.setUserName(userName);
                    int check = attendanceDAO.save(attendance);
                    if(check>0)
                    {
                        new MessageForm("Success","Your attendance for today has been recorded.","info.png").setVisible(true);
                    }else
                    {
                        new MessageForm("Error","Your attendance for today already exist.","error.png").setVisible(true);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(UserAttendanceFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
            } else {
                new MessageForm("Error", "Wrong username and password", "error.png").setVisible(true);
            }

        } else if (!userField.getText().trim().equals("") || !passField.getText().trim().equals("")) {
            System.err.println("Checking with email");
            userModel = new User();
            userModel.setEmail(userField.getText());
            userModel.setPassword(passField.getText());
            userModel = new UserDaoImpl().loginUser(userModel);
            if (userModel != null && userModel.getDesignation().equalsIgnoreCase("Admin")) {
                new MainFrame().setVisible(true);
                this.dispose();
            } else if (userModel != null) {
                new GeneralUserFrame().setVisible(true);
                this.dispose();
            } else {
                new MessageForm("Error", "Wrong email or password", "error.png").setVisible(true);
            }
        } else {
            new MessageForm("Error", "Fields are empty", "error.png").setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAuthenticate;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables

    private void signUp() {
        new SignUpFrame().setVisible(true);
        this.dispose();
    }
}
