/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.payroll.business;

import com.payroll.dao.UserDAO;
import com.payroll.daoimpl.UserDaoImpl;
import com.payroll.models.User;
import com.payroll.utility.CommonMethods;
import java.awt.event.KeyEvent;
import javax.swing.JPasswordField;

/**
 *
 * @author Kashif Alei
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        lblAuthenticate = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        firstNameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        userTypeCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registeration");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, -1));

        jLabel8.setBackground(new java.awt.Color(53, 168, 83));
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 70));

        lblLogin.setBackground(new java.awt.Color(53, 168, 83));
        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Sign up");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setOpaque(true);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 670, 230, 50));

        userNameField.setBackground(new java.awt.Color(250, 250, 250));
        userNameField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        userNameField.setForeground(new java.awt.Color(102, 102, 102));
        userNameField.setText("USERNAME");
        userNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFieldFocusLost(evt);
            }
        });
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameFieldKeyPressed(evt);
            }
        });
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 320, 50));

        lblAuthenticate.setBackground(new java.awt.Color(53, 168, 83));
        lblAuthenticate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAuthenticate.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthenticate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthenticate.setText("Cancel");
        lblAuthenticate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAuthenticate.setOpaque(true);
        lblAuthenticate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuthenticateMouseClicked(evt);
            }
        });
        getContentPane().add(lblAuthenticate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 230, 50));

        confirmPasswordField.setBackground(new java.awt.Color(250, 250, 250));
        confirmPasswordField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        confirmPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        confirmPasswordField.setText("PASSWORD");
        confirmPasswordField.setToolTipText("Confirm Password");
        confirmPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordFieldFocusLost(evt);
            }
        });
        confirmPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmPasswordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 320, 50));

        passwordField.setBackground(new java.awt.Color(250, 250, 250));
        passwordField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        passwordField.setForeground(new java.awt.Color(102, 102, 102));
        passwordField.setText("PASSWORD");
        passwordField.setToolTipText("Password");
        passwordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 320, 50));

        firstNameField.setBackground(new java.awt.Color(250, 250, 250));
        firstNameField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(102, 102, 102));
        firstNameField.setText("FIRST NAME");
        firstNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });
        firstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNameFieldKeyPressed(evt);
            }
        });
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 320, 50));

        emailField.setBackground(new java.awt.Color(250, 250, 250));
        emailField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setText("EMAIL");
        emailField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailFieldKeyPressed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 320, 50));

        phoneField.setBackground(new java.awt.Color(250, 250, 250));
        phoneField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        phoneField.setForeground(new java.awt.Color(102, 102, 102));
        phoneField.setText("PHONE NO");
        phoneField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFieldFocusLost(evt);
            }
        });
        phoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneFieldKeyPressed(evt);
            }
        });
        getContentPane().add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 320, 50));

        lastNameField.setBackground(new java.awt.Color(250, 250, 250));
        lastNameField.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(102, 102, 102));
        lastNameField.setText("LAST NAME");
        lastNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        lastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyPressed(evt);
            }
        });
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 320, 50));

        userTypeCombo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        userTypeCombo.setForeground(new java.awt.Color(102, 102, 102));
        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User type", "Admin", "HR", "Accountant" }));
        userTypeCombo.setBorder(null);
        userTypeCombo.setOpaque(false);
        getContentPane().add(userTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 320, 50));

        addressField.setColumns(20);
        addressField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addressField.setForeground(new java.awt.Color(102, 102, 102));
        addressField.setRows(5);
        addressField.setText("ADDRESS");
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(addressField);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 780, 120));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 940, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        String firstName = firstNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String userName = userNameField.getText().trim();
        String email = emailField.getText().trim();
        String password = passwordField.getText().trim();
        String confirmPassword = passwordField.getText().trim();
        String userType = userTypeCombo.getSelectedItem().toString().trim();
        String address = addressField.getText().trim();
        String phoneNo = phoneField.getText().trim();
        
        User userModel = new User();
        userModel.setAddress(address);
        userModel.setUserName(userName);
        userModel.setEmail(email);
        userModel.setDesignation(userType);
        userModel.setFirstName(firstName);
        userModel.setLastName(lastName);
        userModel.setPassword(password);
        userModel.setPhoneNumber(phoneNo);
        userModel.setStatus("Registered");
        
        System.err.println("Called..");
        if(firstName.trim().isEmpty() || lastName.trim().isEmpty() || userName.trim().isEmpty()
                || password.trim().isEmpty() || confirmPassword.trim().isEmpty() || userType.trim().equals("Select User type")
                || address.trim().isEmpty() || phoneNo.trim().isEmpty())
        {
            new MessageForm("Error","Some fields are missing.","error.png").setVisible(true);
            return;
        }else if(!password.equals(confirmPassword))
        {
            new MessageForm("Error","Password does not match.","error.png").setVisible(true);
            return;            
        }
        UserDAO userDAO = new UserDaoImpl();
        int check = userDAO.registerUser(userModel);
        
        if(check>0)
        {
            new MessageForm("Success","User has been registered successfully.","info.png").setVisible(true);
            this.dispose();
            new LoginFrame().setVisible(true);
        }else
        {
            new MessageForm("Error","Could not save the user, try again.","error.png").setVisible(true);
        }
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblAuthenticateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthenticateMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblAuthenticateMouseClicked

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained
        // TODO add your handling code here:
        if(userNameField.getText().equals("USERNAME")){
            userNameField.setText("");
        }
    }//GEN-LAST:event_userNameFieldFocusGained

    private void userNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusLost
        // TODO add your handling code here:
        if(userNameField.getText().isEmpty()){
            userNameField.setText("USERNAME");
        }
    }//GEN-LAST:event_userNameFieldFocusLost

    private void userNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldKeyPressed

    private void confirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFieldFocusGained
        // TODO add your handling code here:
        if(confirmPasswordField.getText().equals("PASSWORD")){
            confirmPasswordField.setEchoChar(new JPasswordField().getEchoChar());
            confirmPasswordField.setText("");
        }
    }//GEN-LAST:event_confirmPasswordFieldFocusGained

    private void confirmPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFieldFocusLost
        // TODO add your handling code here:
        if(confirmPasswordField.getText().isEmpty()){
            confirmPasswordField.setText("PASSWORD");
            confirmPasswordField.setEchoChar(new JPasswordField().getEchoChar());
        }
    }//GEN-LAST:event_confirmPasswordFieldFocusLost

    private void confirmPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordFieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(lblLogin.isEnabled()){
                
            }

        }
    }//GEN-LAST:event_confirmPasswordFieldKeyPressed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldFocusGained

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void firstNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldKeyPressed

    private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldFocusGained

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void lastNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldKeyPressed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldFocusLost

    private void emailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldKeyPressed

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldFocusGained

    private void phoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldFocusLost

    private void phoneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldKeyPressed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        if(addressField.getText().equals("ADDRESS")){
            addressField.setText("");
        }
    }//GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
        if(addressField.getText().isEmpty()){
            addressField.setText("ADDRESS");
        }
    }//GEN-LAST:event_addressFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressField;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lblAuthenticate;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JComboBox<String> userTypeCombo;
    // End of variables declaration//GEN-END:variables

}
