/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.payroll.business;

import com.payroll.dao.AttendanceDAO;
import com.payroll.daoimpl.AttendanceDAOImpl;
import com.payroll.models.Attendance;
import com.payroll.utility.CommonMethods;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kashif Alei
 */
public class UserAttendanceFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserAttendanceFrame
     */
    private String pattern = "yyyy-MM-dd";
    private SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
    private AttendanceDAOImpl attendanceDAO = new AttendanceDAOImpl();
    public UserAttendanceFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        populateAttendanceTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        attendanceSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        addAttendanceBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(53, 168, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Attendance");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(552, 552, 552)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search Attendance");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, 26));

        attendanceSearch.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        attendanceSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceSearchActionPerformed(evt);
            }
        });
        attendanceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                attendanceSearchKeyReleased(evt);
            }
        });
        jPanel2.add(attendanceSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 220, -1));

        attendanceTable.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        attendanceTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceTable.setRowHeight(20);
        attendanceTable.setSelectionBackground(new java.awt.Color(11, 18, 29));
        attendanceTable.setSelectionForeground(new java.awt.Color(140, 198, 62));
        attendanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                attendanceTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(attendanceTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 1330, 580));

        addAttendanceBtn.setBackground(new java.awt.Color(53, 168, 83));
        addAttendanceBtn.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        addAttendanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        addAttendanceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttendanceBtn.setText("Record Today's Attendance");
        addAttendanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAttendanceBtn.setOpaque(true);
        addAttendanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAttendanceBtnMouseClicked(evt);
            }
        });
        jPanel2.add(addAttendanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void attendanceSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceSearchActionPerformed

    }//GEN-LAST:event_attendanceSearchActionPerformed

    private void attendanceSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendanceSearchKeyReleased
        CommonMethods.searchFromTable(attendanceTable, attendanceSearch);
    }//GEN-LAST:event_attendanceSearchKeyReleased

    private void attendanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceTableMouseClicked

    }//GEN-LAST:event_attendanceTableMouseClicked

    private void attendanceTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceTableMouseReleased

    }//GEN-LAST:event_attendanceTableMouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void addAttendanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAttendanceBtnMouseClicked
        if(addAttendanceBtn.isEnabled()){
            try {
                Date todaysAttendaceDate = new Date();
                String date = simpleDateFormat.format(todaysAttendaceDate);
                String userName = LoginFrame.userModel.getUserName();
                Attendance attendance = new Attendance();
                attendance.setAttendanceDate(simpleDateFormat.parse(date));
                attendance.setUserName(userName);
                int check = attendanceDAO.save(attendance);
                if(check>0)
                {
                    populateAttendanceTable();
                    new MessageForm("Success","Your attendance for today has been added successfully.","info.png").setVisible(true);
                }else
                {
                    new MessageForm("Error","Your attendance for today already exist.","error.png").setVisible(true);
                }
            } catch (ParseException ex) {
                Logger.getLogger(UserAttendanceFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addAttendanceBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAttendanceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAttendanceBtn;
    private javax.swing.JTextField attendanceSearch;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void populateAttendanceTable() {
        ResultSet resultSet = new AttendanceDAOImpl().findAllAttendancesByUserName(LoginFrame.userModel.getUserName());
        CommonMethods.fillTables(resultSet, attendanceTable, jScrollPane2, this);
    }
}
